spring:
  application:
    name: api-gate-way
  cloud:
    gateway:
      mvc:
        routes:
          - id: book-service
            uri: http://localhost:8089
            predicates:
              - Path=/api/books/**
          - id: author-service
            uri: http://localhost:8088
            predicates:
              - Path=/api/authors/**

server:
  port: 8060
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/



management:
  tracing:
    sampling:
      probability: 1.0





