version: '3'
services:
  db-auth:
    image: postgres:latest
    container_name: book-service-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book-service-db
    ports:
      - "5434:5432"